------------------------------------------------------------------------------------
--tblOtherName (othername_pfile_20190902-20190908.csv)
------------------------------------------------------------------------------------
CREATE TABLE tblOtherName (
	NPI,
	ProviderOtherOrganizationName,
	ProviderOtherOrganizationNameTypeCode 
);


INSERT INTO tblOtherName (
	NPI, 
	ProviderOtherOrganizationName, 
	ProviderOtherOrganizationNameTypeCode
) VALUES (
	"1003464132",
	"Linton Square Pharmacy and Medical Supplies, Inc.",
	"5"
);

------------------------------------------------------------------------------------
--tblProviderAltLocation (pl_pfile_20190902-20190908.csv)
------------------------------------------------------------------------------------
CREATE TABLE tblProviderAltLocation (
    NPI,
    ProviderSecondaryPracticeLocationAddressAddressLine1,
    ProviderSecondaryPracticeLocationAddressAddressLine2,
    ProviderSecondaryPracticeLocationAddressCityName,
    ProviderSecondaryPracticeLocationAddressStateName,
    ProviderSecondaryPracticeLocationAddressPostalCode,
    ProviderSecondaryPracticeLocationAddressCountryCode,
    ProviderSecondaryPracticeLocationAddressTelephoneNumber,
    ProviderSecondaryPracticeLocationAddressTelephoneExtension,
    ProviderPracticeLocationAddressFaxNumber 	
);


INSERT INTO tblProviderAltLocation (
    NPI,
    ProviderSecondaryPracticeLocationAddressAddressLine1,
    ProviderSecondaryPracticeLocationAddressAddressLine2,
    ProviderSecondaryPracticeLocationAddressCityName,
    ProviderSecondaryPracticeLocationAddressStateName,
    ProviderSecondaryPracticeLocationAddressPostalCode,
    ProviderSecondaryPracticeLocationAddressCountryCode,
    ProviderSecondaryPracticeLocationAddressTelephoneNumber,
    ProviderSecondaryPracticeLocationAddressTelephoneExtension,
    ProviderPracticeLocationAddressFaxNumber 
) VALUES (
	"1457823486",
	"16301 Sonoma Park Dr",
	"",
	"Edmond",
	"OK",
	"730132091",
	"US",
	"4054220720",
	"",
	""
);

------------------------------------------------------------------------------------
--tblEndpoint (endpoint_pfile_20190902-20190908.csv)
------------------------------------------------------------------------------------
CREATE TABLE tblEndpoint (
	NPI INTEGER NULL,
	EndpointType TEXT NULL,
	EndpointTypeDescription TEXT NULL,
	Endpoint TEXT NULL,
	Affiliation TEXT NULL,
	EndpointDescription TEXT NULL,
	AffiliationLegalBusinessName TEXT NULL,
	UseCode TEXT NULL,
	UseDescription TEXT NULL,
	OtherUseDescription TEXT NULL,
	ContentType TEXT NULL,
	ContentDescription TEXT NULL,
	OtherContentDescription TEXT NULL,
	AffiliationAddressLineOne TEXT NULL,
	AffiliationAddressLineTwo TEXT NULL,
	AffiliationAddressCity TEXT NULL,
	AffiliationAddressState TEXT NULL,
	AffiliationAddressCountry TEXT NULL,
	AffiliationAddressPostalCode INTEGER NULL
);


INSERT INTO tblEndpoint (
	NPI,
	EndpointType,
	EndpointTypeDescription,
	Endpoint,
	Affiliation,
	EndpointDescription,
	AffiliationLegalBusinessName,
	UseCode,
	UseDescription,
	OtherUseDescription,
	ContentType,
	ContentDescription,
	OtherContentDescription,
	AffiliationAddressLineOne,
	AffiliationAddressLineTwo,
	AffiliationAddressCity,
	AffiliationAddressState,
	AffiliationAddressCountry,
	AffiliationAddressPostalCode 
) VALUES (
	1972961068,
	"DIRECT",
	"Direct Messaging Address",
	"aline@cpaucga.com",
	"N",
	"secure work e-mail",
	null,
	"DIRECT",
	"Direct",
	null,
	"CSV",
	"CSV",
	null,
	"6131 S Norcross Tucker Rd",
	null,
	"Norcross",
	"GA",
	"US",
	300935536
)

------------------------------------------------------------------------------------
--tblNpi (npidata_pfile_20190902-20190908.csv)
------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tblNpi (
	NPI INTEGER NULL,
	EntityTypeCode INTEGER NULL,
	ReplacementNPI INTEGER NULL,
	EmployerIdentificationNumberEIN TEXT NULL,
	ProviderOrganizationNameLegalBusinessName TEXT NULL,
	ProviderLastNameLegalName TEXT NULL,
	ProviderFirstName TEXT NULL,
	ProviderMiddleName TEXT NULL,
	ProviderNamePrefixText TEXT NULL,
	ProviderNameSuffixText TEXT NULL,
	ProviderCredentialText TEXT NULL,
	ProviderOtherOrganizationName TEXT NULL,
	ProviderOtherOrganizationNameTypeCode INTEGER NULL,
	ProviderOtherLastName TEXT NULL,
	ProviderOtherFirstName TEXT NULL,
	ProviderOtherMiddleName TEXT NULL,
	ProviderOtherNamePrefixText TEXT NULL,
	ProviderOtherNameSuffixText TEXT NULL,
	ProviderOtherCredentialText TEXT NULL,
	ProviderOtherLastNameTypeCode TEXT NULL,
	ProviderFirstLineBusinessMailingAddress TEXT NULL,
	ProviderSecondLineBusinessMailingAddress TEXT NULL,
	ProviderBusinessMailingAddressCityName TEXT NULL,
	ProviderBusinessMailingAddressStateName TEXT NULL,
	ProviderBusinessMailingAddressPostalCode INTEGER NULL,
	ProviderBusinessMailingAddressCountryCodeIfoutsideUS TEXT NULL,
	ProviderBusinessMailingAddressTelephoneNumber INTEGER NULL,
	ProviderBusinessMailingAddressFaxNumber INTEGER NULL,
	ProviderFirstLineBusinessPracticeLocationAddress TEXT NULL,
	ProviderSecondLineBusinessPracticeLocationAddress TEXT NULL,
	ProviderBusinessPracticeLocationAddressCityName TEXT NULL,
	ProviderBusinessPracticeLocationAddressStateName TEXT NULL,
	ProviderBusinessPracticeLocationAddressPostalCode INTEGER NULL,
	ProviderBusinessPracticeLocationAddressCountryCodeIfoutsideUS TEXT NULL,
	ProviderBusinessPracticeLocationAddressTelephoneNumber INTEGER NULL,
	ProviderBusinessPracticeLocationAddressFaxNumber INTEGER NULL,
	ProviderEnumerationDate TEXT NULL,
	LastUpdateDate TEXT NULL,
	NPIDeactivationReasonCode TEXT NULL,
	NPIDeactivationDate TEXT NULL,
	NPIReactivationDate TEXT NULL,
	ProviderGenderCode TEXT NULL,
	AuthorizedOfficialLastName TEXT NULL,
	AuthorizedOfficialFirstName TEXT NULL,
	AuthorizedOfficialMiddleName TEXT NULL,
	AuthorizedOfficialTitleorPosition TEXT NULL,
	AuthorizedOfficialTelephoneNumber INTEGER NULL,
	HealthcareProviderTaxonomyCode_1 TEXT NULL,
	ProviderLicenseNumber_1 TEXT NULL,
	ProviderLicenseNumberStateCode_1 TEXT NULL,
	HealthcareProviderPrimaryTaxonomySwitch_1 TEXT NULL,
	HealthcareProviderTaxonomyCode_2 TEXT NULL,
	ProviderLicenseNumber_2 TEXT NULL,
	ProviderLicenseNumberStateCode_2 TEXT NULL,
	HealthcareProviderPrimaryTaxonomySwitch_2 TEXT NULL,
	HealthcareProviderTaxonomyCode_3 TEXT NULL,
	ProviderLicenseNumber_3 TEXT NULL,
	ProviderLicenseNumberStateCode_3 TEXT NULL,
	HealthcareProviderPrimaryTaxonomySwitch_3 TEXT NULL,
	HealthcareProviderTaxonomyCode_4 TEXT NULL,
	ProviderLicenseNumber_4 TEXT NULL,
	ProviderLicenseNumberStateCode_4 TEXT NULL,
	HealthcareProviderPrimaryTaxonomySwitch_4 TEXT NULL,
	HealthcareProviderTaxonomyCode_5 TEXT NULL,
	ProviderLicenseNumber_5 TEXT NULL,
	ProviderLicenseNumberStateCode_5 TEXT NULL,
	HealthcareProviderPrimaryTaxonomySwitch_5 TEXT NULL,
	HealthcareProviderTaxonomyCode_6 TEXT NULL,
	ProviderLicenseNumber_6 TEXT NULL,
	ProviderLicenseNumberStateCode_6 TEXT NULL,
	HealthcareProviderPrimaryTaxonomySwitch_6 TEXT NULL,
	HealthcareProviderTaxonomyCode_7 TEXT NULL,
	ProviderLicenseNumber_7 TEXT NULL,
	ProviderLicenseNumberStateCode_7 TEXT NULL,
	HealthcareProviderPrimaryTaxonomySwitch_7 TEXT NULL,
	HealthcareProviderTaxonomyCode_8 TEXT NULL,
	ProviderLicenseNumber_8 TEXT NULL,
	ProviderLicenseNumberStateCode_8 TEXT NULL,
	HealthcareProviderPrimaryTaxonomySwitch_8 TEXT NULL,
	HealthcareProviderTaxonomyCode_9 TEXT NULL,
	ProviderLicenseNumber_9 TEXT NULL,
	ProviderLicenseNumberStateCode_9 TEXT NULL,
	HealthcareProviderPrimaryTaxonomySwitch_9 TEXT NULL,
	HealthcareProviderTaxonomyCode_10 TEXT NULL,
	ProviderLicenseNumber_10 TEXT NULL,
	ProviderLicenseNumberStateCode_10 TEXT NULL,
	HealthcareProviderPrimaryTaxonomySwitch_10 TEXT NULL,
	HealthcareProviderTaxonomyCode_11 TEXT NULL,
	ProviderLicenseNumber_11 TEXT NULL,
	ProviderLicenseNumberStateCode_11 TEXT NULL,
	HealthcareProviderPrimaryTaxonomySwitch_11 TEXT NULL,
	HealthcareProviderTaxonomyCode_12 TEXT NULL,
	ProviderLicenseNumber_12 TEXT NULL,
	ProviderLicenseNumberStateCode_12 TEXT NULL,
	HealthcareProviderPrimaryTaxonomySwitch_12 TEXT NULL,
	HealthcareProviderTaxonomyCode_13 TEXT NULL,
	ProviderLicenseNumber_13 TEXT NULL,
	ProviderLicenseNumberStateCode_13 TEXT NULL,
	HealthcareProviderPrimaryTaxonomySwitch_13 TEXT NULL,
	HealthcareProviderTaxonomyCode_14 TEXT NULL,
	ProviderLicenseNumber_14 TEXT NULL,
	ProviderLicenseNumberStateCode_14 TEXT NULL,
	HealthcareProviderPrimaryTaxonomySwitch_14 TEXT NULL,
	HealthcareProviderTaxonomyCode_15 TEXT NULL,
	ProviderLicenseNumber_15 TEXT NULL,
	ProviderLicenseNumberStateCode_15 TEXT NULL,
	HealthcareProviderPrimaryTaxonomySwitch_15 TEXT NULL,
	OtherProviderIdentifier_1 TEXT NULL,
	OtherProviderIdentifierTypeCode_1 INTEGER NULL,
	OtherProviderIdentifierState_1 TEXT NULL,
	OtherProviderIdentifierIssuer_1 TEXT NULL,
	OtherProviderIdentifier_2 TEXT NULL,
	OtherProviderIdentifierTypeCode_2 INTEGER NULL,
	OtherProviderIdentifierState_2 TEXT NULL,
	OtherProviderIdentifierIssuer_2 TEXT NULL,
	OtherProviderIdentifier_3 TEXT NULL,
	OtherProviderIdentifierTypeCode_3 INTEGER NULL,
	OtherProviderIdentifierState_3 TEXT NULL,
	OtherProviderIdentifierIssuer_3 TEXT NULL,
	OtherProviderIdentifier_4 TEXT NULL,
	OtherProviderIdentifierTypeCode_4 INTEGER NULL,
	OtherProviderIdentifierState_4 TEXT NULL,
	OtherProviderIdentifierIssuer_4 TEXT NULL,
	OtherProviderIdentifier_5 TEXT NULL,
	OtherProviderIdentifierTypeCode_5 INTEGER NULL,
	OtherProviderIdentifierState_5 TEXT NULL,
	OtherProviderIdentifierIssuer_5 TEXT NULL,
	OtherProviderIdentifier_6 TEXT NULL,
	OtherProviderIdentifierTypeCode_6 INTEGER NULL,
	OtherProviderIdentifierState_6 TEXT NULL,
	OtherProviderIdentifierIssuer_6 TEXT NULL,
	OtherProviderIdentifier_7 TEXT NULL,
	OtherProviderIdentifierTypeCode_7 INTEGER NULL,
	OtherProviderIdentifierState_7 TEXT NULL,
	OtherProviderIdentifierIssuer_7 TEXT NULL,
	OtherProviderIdentifier_8 TEXT NULL,
	OtherProviderIdentifierTypeCode_8 INTEGER NULL,
	OtherProviderIdentifierState_8 TEXT NULL,
	OtherProviderIdentifierIssuer_8 TEXT NULL,
	OtherProviderIdentifier_9 TEXT NULL,
	OtherProviderIdentifierTypeCode_9 INTEGER NULL,
	OtherProviderIdentifierState_9 TEXT NULL,
	OtherProviderIdentifierIssuer_9 TEXT NULL,
	OtherProviderIdentifier_10 TEXT NULL,
	OtherProviderIdentifierTypeCode_10 INTEGER NULL,
	OtherProviderIdentifierState_10 TEXT NULL,
	OtherProviderIdentifierIssuer_10 TEXT NULL,
	OtherProviderIdentifier_11 TEXT NULL,
	OtherProviderIdentifierTypeCode_11 INTEGER NULL,
	OtherProviderIdentifierState_11 TEXT NULL,
	OtherProviderIdentifierIssuer_11 TEXT NULL,
	OtherProviderIdentifier_12 TEXT NULL,
	OtherProviderIdentifierTypeCode_12 INTEGER NULL,
	OtherProviderIdentifierState_12 TEXT NULL,
	OtherProviderIdentifierIssuer_12 TEXT NULL,
	OtherProviderIdentifier_13 TEXT NULL,
	OtherProviderIdentifierTypeCode_13 INTEGER NULL,
	OtherProviderIdentifierState_13 TEXT NULL,
	OtherProviderIdentifierIssuer_13 TEXT NULL,
	OtherProviderIdentifier_14 TEXT NULL,
	OtherProviderIdentifierTypeCode_14 INTEGER NULL,
	OtherProviderIdentifierState_14 TEXT NULL,
	OtherProviderIdentifierIssuer_14 TEXT NULL,
	OtherProviderIdentifier_15 TEXT NULL,
	OtherProviderIdentifierTypeCode_15 INTEGER NULL,
	OtherProviderIdentifierState_15 TEXT NULL,
	OtherProviderIdentifierIssuer_15 TEXT NULL,
	OtherProviderIdentifier_16 TEXT NULL,
	OtherProviderIdentifierTypeCode_16 INTEGER NULL,
	OtherProviderIdentifierState_16 TEXT NULL,
	OtherProviderIdentifierIssuer_16 TEXT NULL,
	OtherProviderIdentifier_17 TEXT NULL,
	OtherProviderIdentifierTypeCode_17 INTEGER NULL,
	OtherProviderIdentifierState_17 TEXT NULL,
	OtherProviderIdentifierIssuer_17 TEXT NULL,
	OtherProviderIdentifier_18 TEXT NULL,
	OtherProviderIdentifierTypeCode_18 INTEGER NULL,
	OtherProviderIdentifierState_18 TEXT NULL,
	OtherProviderIdentifierIssuer_18 TEXT NULL,
	OtherProviderIdentifier_19 TEXT NULL,
	OtherProviderIdentifierTypeCode_19 INTEGER NULL,
	OtherProviderIdentifierState_19 TEXT NULL,
	OtherProviderIdentifierIssuer_19 TEXT NULL,
	OtherProviderIdentifier_20 TEXT NULL,
	OtherProviderIdentifierTypeCode_20 INTEGER NULL,
	OtherProviderIdentifierState_20 TEXT NULL,
	OtherProviderIdentifierIssuer_20 TEXT NULL,
	OtherProviderIdentifier_21 TEXT NULL,
	OtherProviderIdentifierTypeCode_21 INTEGER NULL,
	OtherProviderIdentifierState_21 TEXT NULL,
	OtherProviderIdentifierIssuer_21 TEXT NULL,
	OtherProviderIdentifier_22 TEXT NULL,
	OtherProviderIdentifierTypeCode_22 INTEGER NULL,
	OtherProviderIdentifierState_22 TEXT NULL,
	OtherProviderIdentifierIssuer_22 TEXT NULL,
	OtherProviderIdentifier_23 TEXT NULL,
	OtherProviderIdentifierTypeCode_23 INTEGER NULL,
	OtherProviderIdentifierState_23 TEXT NULL,
	OtherProviderIdentifierIssuer_23 TEXT NULL,
	OtherProviderIdentifier_24 TEXT NULL,
	OtherProviderIdentifierTypeCode_24 INTEGER NULL,
	OtherProviderIdentifierState_24 TEXT NULL,
	OtherProviderIdentifierIssuer_24 TEXT NULL,
	OtherProviderIdentifier_25 TEXT NULL,
	OtherProviderIdentifierTypeCode_25 INTEGER NULL,
	OtherProviderIdentifierState_25 TEXT NULL,
	OtherProviderIdentifierIssuer_25 TEXT NULL,
	OtherProviderIdentifier_26 TEXT NULL,
	OtherProviderIdentifierTypeCode_26 INTEGER NULL,
	OtherProviderIdentifierState_26 TEXT NULL,
	OtherProviderIdentifierIssuer_26 TEXT NULL,
	OtherProviderIdentifier_27 TEXT NULL,
	OtherProviderIdentifierTypeCode_27 INTEGER NULL,
	OtherProviderIdentifierState_27 TEXT NULL,
	OtherProviderIdentifierIssuer_27 TEXT NULL,
	OtherProviderIdentifier_28 TEXT NULL,
	OtherProviderIdentifierTypeCode_28 INTEGER NULL,
	OtherProviderIdentifierState_28 TEXT NULL,
	OtherProviderIdentifierIssuer_28 TEXT NULL,
	OtherProviderIdentifier_29 TEXT NULL,
	OtherProviderIdentifierTypeCode_29 INTEGER NULL,
	OtherProviderIdentifierState_29 TEXT NULL,
	OtherProviderIdentifierIssuer_29 TEXT NULL,
	OtherProviderIdentifier_30 TEXT NULL,
	OtherProviderIdentifierTypeCode_30 INTEGER NULL,
	OtherProviderIdentifierState_30 TEXT NULL,
	OtherProviderIdentifierIssuer_30 TEXT NULL,
	OtherProviderIdentifier_31 TEXT NULL,
	OtherProviderIdentifierTypeCode_31 INTEGER NULL,
	OtherProviderIdentifierState_31 TEXT NULL,
	OtherProviderIdentifierIssuer_31 TEXT NULL,
	OtherProviderIdentifier_32 TEXT NULL,
	OtherProviderIdentifierTypeCode_32 INTEGER NULL,
	OtherProviderIdentifierState_32 TEXT NULL,
	OtherProviderIdentifierIssuer_32 TEXT NULL,
	OtherProviderIdentifier_33 TEXT NULL,
	OtherProviderIdentifierTypeCode_33 INTEGER NULL,
	OtherProviderIdentifierState_33 TEXT NULL,
	OtherProviderIdentifierIssuer_33 TEXT NULL,
	OtherProviderIdentifier_34 TEXT NULL,
	OtherProviderIdentifierTypeCode_34 INTEGER NULL,
	OtherProviderIdentifierState_34 TEXT NULL,
	OtherProviderIdentifierIssuer_34 TEXT NULL,
	OtherProviderIdentifier_35 TEXT NULL,
	OtherProviderIdentifierTypeCode_35 INTEGER NULL,
	OtherProviderIdentifierState_35 TEXT NULL,
	OtherProviderIdentifierIssuer_35 TEXT NULL,
	OtherProviderIdentifier_36 TEXT NULL,
	OtherProviderIdentifierTypeCode_36 INTEGER NULL,
	OtherProviderIdentifierState_36 TEXT NULL,
	OtherProviderIdentifierIssuer_36 TEXT NULL,
	OtherProviderIdentifier_37 TEXT NULL,
	OtherProviderIdentifierTypeCode_37 INTEGER NULL,
	OtherProviderIdentifierState_37 TEXT NULL,
	OtherProviderIdentifierIssuer_37 TEXT NULL,
	OtherProviderIdentifier_38 TEXT NULL,
	OtherProviderIdentifierTypeCode_38 INTEGER NULL,
	OtherProviderIdentifierState_38 TEXT NULL,
	OtherProviderIdentifierIssuer_38 TEXT NULL,
	OtherProviderIdentifier_39 TEXT NULL,
	OtherProviderIdentifierTypeCode_39 INTEGER NULL,
	OtherProviderIdentifierState_39 TEXT NULL,
	OtherProviderIdentifierIssuer_39 TEXT NULL,
	OtherProviderIdentifier_40 TEXT NULL,
	OtherProviderIdentifierTypeCode_40 INTEGER NULL,
	OtherProviderIdentifierState_40 TEXT NULL,
	OtherProviderIdentifierIssuer_40 TEXT NULL,
	OtherProviderIdentifier_41 TEXT NULL,
	OtherProviderIdentifierTypeCode_41 INTEGER NULL,
	OtherProviderIdentifierState_41 TEXT NULL,
	OtherProviderIdentifierIssuer_41 TEXT NULL,
	OtherProviderIdentifier_42 TEXT NULL,
	OtherProviderIdentifierTypeCode_42 INTEGER NULL,
	OtherProviderIdentifierState_42 TEXT NULL,
	OtherProviderIdentifierIssuer_42 TEXT NULL,
	OtherProviderIdentifier_43 TEXT NULL,
	OtherProviderIdentifierTypeCode_43 INTEGER NULL,
	OtherProviderIdentifierState_43 TEXT NULL,
	OtherProviderIdentifierIssuer_43 TEXT NULL,
	OtherProviderIdentifier_44 TEXT NULL,
	OtherProviderIdentifierTypeCode_44 INTEGER NULL,
	OtherProviderIdentifierState_44 TEXT NULL,
	OtherProviderIdentifierIssuer_44 TEXT NULL,
	OtherProviderIdentifier_45 TEXT NULL,
	OtherProviderIdentifierTypeCode_45 INTEGER NULL,
	OtherProviderIdentifierState_45 TEXT NULL,
	OtherProviderIdentifierIssuer_45 TEXT NULL,
	OtherProviderIdentifier_46 TEXT NULL,
	OtherProviderIdentifierTypeCode_46 INTEGER NULL,
	OtherProviderIdentifierState_46 TEXT NULL,
	OtherProviderIdentifierIssuer_46 TEXT NULL,
	OtherProviderIdentifier_47 TEXT NULL,
	OtherProviderIdentifierTypeCode_47 INTEGER NULL,
	OtherProviderIdentifierState_47 TEXT NULL,
	OtherProviderIdentifierIssuer_47 TEXT NULL,
	OtherProviderIdentifier_48 TEXT NULL,
	OtherProviderIdentifierTypeCode_48 INTEGER NULL,
	OtherProviderIdentifierState_48 TEXT NULL,
	OtherProviderIdentifierIssuer_48 TEXT NULL,
	OtherProviderIdentifier_49 TEXT NULL,
	OtherProviderIdentifierTypeCode_49 INTEGER NULL,
	OtherProviderIdentifierState_49 TEXT NULL,
	OtherProviderIdentifierIssuer_49 TEXT NULL,
	OtherProviderIdentifier_50 TEXT NULL,
	OtherProviderIdentifierTypeCode_50 INTEGER NULL,
	OtherProviderIdentifierState_50 TEXT NULL,
	OtherProviderIdentifierIssuer_50 TEXT NULL,
	IsSoleProprietor TEXT NULL,
	IsOrganizationSubpart TEXT NULL,
	ParentOrganizationLBN TEXT NULL,
	ParentOrganizationTIN TEXT NULL,
	AuthorizedOfficialNamePrefixText TEXT NULL,
	AuthorizedOfficialNameSuffixText TEXT NULL,
	AuthorizedOfficialCredentialText TEXT NULL,
	HealthcareProviderTaxonomyGroup_1 TEXT NULL,
	HealthcareProviderTaxonomyGroup_2 TEXT NULL,
	HealthcareProviderTaxonomyGroup_3 TEXT NULL,
	HealthcareProviderTaxonomyGroup_4 TEXT NULL,
	HealthcareProviderTaxonomyGroup_5 TEXT NULL,
	HealthcareProviderTaxonomyGroup_6 TEXT NULL,
	HealthcareProviderTaxonomyGroup_7 TEXT NULL,
	HealthcareProviderTaxonomyGroup_8 TEXT NULL,
	HealthcareProviderTaxonomyGroup_9 TEXT NULL,
	HealthcareProviderTaxonomyGroup_10 TEXT NULL,
	HealthcareProviderTaxonomyGroup_11 TEXT NULL,
	HealthcareProviderTaxonomyGroup_12 TEXT NULL,
	HealthcareProviderTaxonomyGroup_13 TEXT NULL,
	HealthcareProviderTaxonomyGroup_14 TEXT NULL,
	HealthcareProviderTaxonomyGroup_15 TEXT NULL
);

INSERT INTO tblNpi (
	NPI,
	EntityTypeCode,
	ReplacementNPI,
	EmployerIdentificationNumberEIN,
	ProviderOrganizationNameLegalBusinessName,
	ProviderLastNameLegalName,
	ProviderFirstName,
	ProviderMiddleName,
	ProviderNamePrefixText,
	ProviderNameSuffixText,
	ProviderCredentialText,
	ProviderOtherOrganizationName,
	ProviderOtherOrganizationNameTypeCode,
	ProviderOtherLastName,
	ProviderOtherFirstName,
	ProviderOtherMiddleName,
	ProviderOtherNamePrefixText,
	ProviderOtherNameSuffixText,
	ProviderOtherCredentialText,
	ProviderOtherLastNameTypeCode,
	ProviderFirstLineBusinessMailingAddress,
	ProviderSecondLineBusinessMailingAddress,
	ProviderBusinessMailingAddressCityName,
	ProviderBusinessMailingAddressStateName,
	ProviderBusinessMailingAddressPostalCode,
	ProviderBusinessMailingAddressCountryCodeIfoutsideUS,
	ProviderBusinessMailingAddressTelephoneNumber,
	ProviderBusinessMailingAddressFaxNumber,
	ProviderFirstLineBusinessPracticeLocationAddress,
	ProviderSecondLineBusinessPracticeLocationAddress,
	ProviderBusinessPracticeLocationAddressCityName,
	ProviderBusinessPracticeLocationAddressStateName,
	ProviderBusinessPracticeLocationAddressPostalCode,
	ProviderBusinessPracticeLocationAddressCountryCodeIfoutsideUS,
	ProviderBusinessPracticeLocationAddressTelephoneNumber,
	ProviderBusinessPracticeLocationAddressFaxNumber,
	ProviderEnumerationDate,
	LastUpdateDate,
	NPIDeactivationReasonCode,
	NPIDeactivationDate,
	NPIReactivationDate,
	ProviderGenderCode,
	AuthorizedOfficialLastName,
	AuthorizedOfficialFirstName,
	AuthorizedOfficialMiddleName,
	AuthorizedOfficialTitleorPosition,
	AuthorizedOfficialTelephoneNumber,
	HealthcareProviderTaxonomyCode_1,
	ProviderLicenseNumber_1,
	ProviderLicenseNumberStateCode_1,
	HealthcareProviderPrimaryTaxonomySwitch_1,
	HealthcareProviderTaxonomyCode_2,
	ProviderLicenseNumber_2,
	ProviderLicenseNumberStateCode_2,
	HealthcareProviderPrimaryTaxonomySwitch_2,
	HealthcareProviderTaxonomyCode_3,
	ProviderLicenseNumber_3,
	ProviderLicenseNumberStateCode_3,
	HealthcareProviderPrimaryTaxonomySwitch_3,
	HealthcareProviderTaxonomyCode_4,
	ProviderLicenseNumber_4,
	ProviderLicenseNumberStateCode_4,
	HealthcareProviderPrimaryTaxonomySwitch_4,
	HealthcareProviderTaxonomyCode_5,
	ProviderLicenseNumber_5,
	ProviderLicenseNumberStateCode_5,
	HealthcareProviderPrimaryTaxonomySwitch_5,
	HealthcareProviderTaxonomyCode_6,
	ProviderLicenseNumber_6,
	ProviderLicenseNumberStateCode_6,
	HealthcareProviderPrimaryTaxonomySwitch_6,
	HealthcareProviderTaxonomyCode_7,
	ProviderLicenseNumber_7,
	ProviderLicenseNumberStateCode_7,
	HealthcareProviderPrimaryTaxonomySwitch_7,
	HealthcareProviderTaxonomyCode_8,
	ProviderLicenseNumber_8,
	ProviderLicenseNumberStateCode_8,
	HealthcareProviderPrimaryTaxonomySwitch_8,
	HealthcareProviderTaxonomyCode_9,
	ProviderLicenseNumber_9,
	ProviderLicenseNumberStateCode_9,
	HealthcareProviderPrimaryTaxonomySwitch_9,
	HealthcareProviderTaxonomyCode_10,
	ProviderLicenseNumber_10,
	ProviderLicenseNumberStateCode_10,
	HealthcareProviderPrimaryTaxonomySwitch_10,
	HealthcareProviderTaxonomyCode_11,
	ProviderLicenseNumber_11,
	ProviderLicenseNumberStateCode_11,
	HealthcareProviderPrimaryTaxonomySwitch_11,
	HealthcareProviderTaxonomyCode_12,
	ProviderLicenseNumber_12,
	ProviderLicenseNumberStateCode_12,
	HealthcareProviderPrimaryTaxonomySwitch_12,
	HealthcareProviderTaxonomyCode_13,
	ProviderLicenseNumber_13,
	ProviderLicenseNumberStateCode_13,
	HealthcareProviderPrimaryTaxonomySwitch_13,
	HealthcareProviderTaxonomyCode_14,
	ProviderLicenseNumber_14,
	ProviderLicenseNumberStateCode_14,
	HealthcareProviderPrimaryTaxonomySwitch_14,
	HealthcareProviderTaxonomyCode_15,
	ProviderLicenseNumber_15,
	ProviderLicenseNumberStateCode_15,
	HealthcareProviderPrimaryTaxonomySwitch_15,
	OtherProviderIdentifier_1,
	OtherProviderIdentifierTypeCode_1,
	OtherProviderIdentifierState_1,
	OtherProviderIdentifierIssuer_1,
	OtherProviderIdentifier_2,
	OtherProviderIdentifierTypeCode_2,
	OtherProviderIdentifierState_2,
	OtherProviderIdentifierIssuer_2,
	OtherProviderIdentifier_3,
	OtherProviderIdentifierTypeCode_3,
	OtherProviderIdentifierState_3,
	OtherProviderIdentifierIssuer_3,
	OtherProviderIdentifier_4,
	OtherProviderIdentifierTypeCode_4,
	OtherProviderIdentifierState_4,
	OtherProviderIdentifierIssuer_4,
	OtherProviderIdentifier_5,
	OtherProviderIdentifierTypeCode_5,
	OtherProviderIdentifierState_5,
	OtherProviderIdentifierIssuer_5,
	OtherProviderIdentifier_6,
	OtherProviderIdentifierTypeCode_6,
	OtherProviderIdentifierState_6,
	OtherProviderIdentifierIssuer_6,
	OtherProviderIdentifier_7,
	OtherProviderIdentifierTypeCode_7,
	OtherProviderIdentifierState_7,
	OtherProviderIdentifierIssuer_7,
	OtherProviderIdentifier_8,
	OtherProviderIdentifierTypeCode_8,
	OtherProviderIdentifierState_8,
	OtherProviderIdentifierIssuer_8,
	OtherProviderIdentifier_9,
	OtherProviderIdentifierTypeCode_9,
	OtherProviderIdentifierState_9,
	OtherProviderIdentifierIssuer_9,
	OtherProviderIdentifier_10,
	OtherProviderIdentifierTypeCode_10,
	OtherProviderIdentifierState_10,
	OtherProviderIdentifierIssuer_10,
	OtherProviderIdentifier_11,
	OtherProviderIdentifierTypeCode_11,
	OtherProviderIdentifierState_11,
	OtherProviderIdentifierIssuer_11,
	OtherProviderIdentifier_12,
	OtherProviderIdentifierTypeCode_12,
	OtherProviderIdentifierState_12,
	OtherProviderIdentifierIssuer_12,
	OtherProviderIdentifier_13,
	OtherProviderIdentifierTypeCode_13,
	OtherProviderIdentifierState_13,
	OtherProviderIdentifierIssuer_13,
	OtherProviderIdentifier_14,
	OtherProviderIdentifierTypeCode_14,
	OtherProviderIdentifierState_14,
	OtherProviderIdentifierIssuer_14,
	OtherProviderIdentifier_15,
	OtherProviderIdentifierTypeCode_15,
	OtherProviderIdentifierState_15,
	OtherProviderIdentifierIssuer_15,
	OtherProviderIdentifier_16,
	OtherProviderIdentifierTypeCode_16,
	OtherProviderIdentifierState_16,
	OtherProviderIdentifierIssuer_16,
	OtherProviderIdentifier_17,
	OtherProviderIdentifierTypeCode_17,
	OtherProviderIdentifierState_17,
	OtherProviderIdentifierIssuer_17,
	OtherProviderIdentifier_18,
	OtherProviderIdentifierTypeCode_18,
	OtherProviderIdentifierState_18,
	OtherProviderIdentifierIssuer_18,
	OtherProviderIdentifier_19,
	OtherProviderIdentifierTypeCode_19,
	OtherProviderIdentifierState_19,
	OtherProviderIdentifierIssuer_19,
	OtherProviderIdentifier_20,
	OtherProviderIdentifierTypeCode_20,
	OtherProviderIdentifierState_20,
	OtherProviderIdentifierIssuer_20,
	OtherProviderIdentifier_21,
	OtherProviderIdentifierTypeCode_21,
	OtherProviderIdentifierState_21,
	OtherProviderIdentifierIssuer_21,
	OtherProviderIdentifier_22,
	OtherProviderIdentifierTypeCode_22,
	OtherProviderIdentifierState_22,
	OtherProviderIdentifierIssuer_22,
	OtherProviderIdentifier_23,
	OtherProviderIdentifierTypeCode_23,
	OtherProviderIdentifierState_23,
	OtherProviderIdentifierIssuer_23,
	OtherProviderIdentifier_24,
	OtherProviderIdentifierTypeCode_24,
	OtherProviderIdentifierState_24,
	OtherProviderIdentifierIssuer_24,
	OtherProviderIdentifier_25,
	OtherProviderIdentifierTypeCode_25,
	OtherProviderIdentifierState_25,
	OtherProviderIdentifierIssuer_25,
	OtherProviderIdentifier_26,
	OtherProviderIdentifierTypeCode_26,
	OtherProviderIdentifierState_26,
	OtherProviderIdentifierIssuer_26,
	OtherProviderIdentifier_27,
	OtherProviderIdentifierTypeCode_27,
	OtherProviderIdentifierState_27,
	OtherProviderIdentifierIssuer_27,
	OtherProviderIdentifier_28,
	OtherProviderIdentifierTypeCode_28,
	OtherProviderIdentifierState_28,
	OtherProviderIdentifierIssuer_28,
	OtherProviderIdentifier_29,
	OtherProviderIdentifierTypeCode_29,
	OtherProviderIdentifierState_29,
	OtherProviderIdentifierIssuer_29,
	OtherProviderIdentifier_30,
	OtherProviderIdentifierTypeCode_30,
	OtherProviderIdentifierState_30,
	OtherProviderIdentifierIssuer_30,
	OtherProviderIdentifier_31,
	OtherProviderIdentifierTypeCode_31,
	OtherProviderIdentifierState_31,
	OtherProviderIdentifierIssuer_31,
	OtherProviderIdentifier_32,
	OtherProviderIdentifierTypeCode_32,
	OtherProviderIdentifierState_32,
	OtherProviderIdentifierIssuer_32,
	OtherProviderIdentifier_33,
	OtherProviderIdentifierTypeCode_33,
	OtherProviderIdentifierState_33,
	OtherProviderIdentifierIssuer_33,
	OtherProviderIdentifier_34,
	OtherProviderIdentifierTypeCode_34,
	OtherProviderIdentifierState_34,
	OtherProviderIdentifierIssuer_34,
	OtherProviderIdentifier_35,
	OtherProviderIdentifierTypeCode_35,
	OtherProviderIdentifierState_35,
	OtherProviderIdentifierIssuer_35,
	OtherProviderIdentifier_36,
	OtherProviderIdentifierTypeCode_36,
	OtherProviderIdentifierState_36,
	OtherProviderIdentifierIssuer_36,
	OtherProviderIdentifier_37,
	OtherProviderIdentifierTypeCode_37,
	OtherProviderIdentifierState_37,
	OtherProviderIdentifierIssuer_37,
	OtherProviderIdentifier_38,
	OtherProviderIdentifierTypeCode_38,
	OtherProviderIdentifierState_38,
	OtherProviderIdentifierIssuer_38,
	OtherProviderIdentifier_39,
	OtherProviderIdentifierTypeCode_39,
	OtherProviderIdentifierState_39,
	OtherProviderIdentifierIssuer_39,
	OtherProviderIdentifier_40,
	OtherProviderIdentifierTypeCode_40,
	OtherProviderIdentifierState_40,
	OtherProviderIdentifierIssuer_40,
	OtherProviderIdentifier_41,
	OtherProviderIdentifierTypeCode_41,
	OtherProviderIdentifierState_41,
	OtherProviderIdentifierIssuer_41,
	OtherProviderIdentifier_42,
	OtherProviderIdentifierTypeCode_42,
	OtherProviderIdentifierState_42,
	OtherProviderIdentifierIssuer_42,
	OtherProviderIdentifier_43,
	OtherProviderIdentifierTypeCode_43,
	OtherProviderIdentifierState_43,
	OtherProviderIdentifierIssuer_43,
	OtherProviderIdentifier_44,
	OtherProviderIdentifierTypeCode_44,
	OtherProviderIdentifierState_44,
	OtherProviderIdentifierIssuer_44,
	OtherProviderIdentifier_45,
	OtherProviderIdentifierTypeCode_45,
	OtherProviderIdentifierState_45,
	OtherProviderIdentifierIssuer_45,
	OtherProviderIdentifier_46,
	OtherProviderIdentifierTypeCode_46,
	OtherProviderIdentifierState_46,
	OtherProviderIdentifierIssuer_46,
	OtherProviderIdentifier_47,
	OtherProviderIdentifierTypeCode_47,
	OtherProviderIdentifierState_47,
	OtherProviderIdentifierIssuer_47,
	OtherProviderIdentifier_48,
	OtherProviderIdentifierTypeCode_48,
	OtherProviderIdentifierState_48,
	OtherProviderIdentifierIssuer_48,
	OtherProviderIdentifier_49,
	OtherProviderIdentifierTypeCode_49,
	OtherProviderIdentifierState_49,
	OtherProviderIdentifierIssuer_49,
	OtherProviderIdentifier_50,
	OtherProviderIdentifierTypeCode_50,
	OtherProviderIdentifierState_50,
	OtherProviderIdentifierIssuer_50,
	IsSoleProprietor,
	IsOrganizationSubpart,
	ParentOrganizationLBN,
	ParentOrganizationTIN,
	AuthorizedOfficialNamePrefixText,
	AuthorizedOfficialNameSuffixText,
	AuthorizedOfficialCredentialText,
	HealthcareProviderTaxonomyGroup_1,
	HealthcareProviderTaxonomyGroup_2,
	HealthcareProviderTaxonomyGroup_3,
	HealthcareProviderTaxonomyGroup_4,
	HealthcareProviderTaxonomyGroup_5,
	HealthcareProviderTaxonomyGroup_6,
	HealthcareProviderTaxonomyGroup_7,
	HealthcareProviderTaxonomyGroup_8,
	HealthcareProviderTaxonomyGroup_9,
	HealthcareProviderTaxonomyGroup_10,
	HealthcareProviderTaxonomyGroup_11,
	HealthcareProviderTaxonomyGroup_12,
	HealthcareProviderTaxonomyGroup_13,
	HealthcareProviderTaxonomyGroup_14,
	HealthcareProviderTaxonomyGroup_15
) VALUES ('1972961068', '1', '', '', '', 'BAYARD', 'ALINE', '', '', '', 'CNP', '', '', '', '', '', '', '', '', '', '6131 S NORCROSS TUCKER RD', '', 'NORCROSS', 'GA', '300935536', 'US', '6782051959', '7705527100', '80 B VETERANS BLVD', '', 'ACOMA', 'NM', '87034', 'US', '5055525300', '5055525490', '02/03/2016', '09/02/2019', '', '', '', 'F', '', '', '', '', '', '363LF0000X', 'RN141931', 'GA', 'Y', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'H3451', '05', 'NM', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'N', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '')
